# Generated by Django 3.1.12 on 2022-08-22 01:12

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('publisher', djongo.models.fields.EmbeddedField(model_container=api.models.Entity)),
                ('author', djongo.models.fields.EmbeddedField(model_container=api.models.Entity)),
                ('image', models.CharField(max_length=200)),
                ('sections', djongo.models.fields.ArrayField(model_container=api.models.Section)),
                ('updated_date', models.CharField(max_length=200)),
            ],
        ),
    ]
